spring:
    # DataSource Config
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: ps97^xn$5qrRgiyf4npIWjn^yq4%2@P44QrA0y*ilJFztntuPt4#S^gOG0FyWN7D
        url: jdbc:mysql://gz-cynosdbmysql-grp-3g2f2hi3.sql.tencentcdb.com:26001/mall

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update